"""Adicionado o campo currency em person v3

Revision ID: e964d1017570
Revises: b48264a90a6b
Create Date: 2022-11-12 09:22:03.975464

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e964d1017570'
down_revision = 'b48264a90a6b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('person', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('person', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
